development:
  netatlas_url: http://netatlas.dev
  netatlas_user: test@netatlas.com
  netatlas_password: password
  logfile: /Users/rmcclain/Projects/netatlas-poller/log/poller.log
  loglevel: debug
  amqp:
    :user: netatlas
    :pass: netatlas
    :host: 127.0.0.1
    :vhost: netatlas_development
  nagios:
    :plugin_dir: /usr/local/sbin

test:
  netatlas_url: http://test.lvh.me:3001
  netatlas_user: test@netatlas.com
  netatlas_password: password
  logfile: /tmp/poller.log
  loglevel: debug
  amqp:
    :user: netatlas
    :pass: netatlas
    :host: 127.0.0.1
    :vhost: netatlas_test
  :nagios:
    :plugin_dir: /usr/local/sbin

staging:
  netatlas_url: http://test.lvh.me
  netatlas_user: test@netatlas.com
  netatlas_password: password
  logfile: /tmp/poller.log
  loglevel: debug
  amqp:
    :user: netatlas
    :pass: netatlas
    :host: 127.0.0.1
    :vhost: netatlas_production
  :nagios:
    :plugin_dir: /usr/local/sbin

production:
  netatlas_url: http://test.lvh.me
  netatlas_user: test@netatlas.com
  netatlas_password: password
  logfile: /tmp/poller.log
  loglevel: debug
  amqp:
    :user: netatlas
    :pass: netatlas
    :host: 127.0.0.1
    :vhost: netatlas_production
  nagios:
    :plugin_dir: /usr/local/sbin

